# Generated by Django 5.0.7 on 2024-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
